DiODeProject/MuMoT

- mumot/__init__.py
Minor PEP8 tweaks.  Primary purpose of this PR is to check if a Travis build is triggered.
> Code cleanup

- .gitignore
- docs/Makefile
- docs/source/_static/css/style.css
- docs/source/_templates/layout.html
- docs/source/api.rst
- docs/source/conf.py
- docs/source/index.rst
- mumot/__init__.py
- setup.py
* Sphinx API docs for public functions plus Model, View, Controller and Exception classes
* Consistent numpydoc-style docstrings
> Sphinx API documentation and doctring improvements

- mumot/__init__.py
> Do not define default param vals as new dicts

- readthedocs.yml
> Add RTD config to ensure RTD builds with Python 3.6

- docs/source/conf.py
> Disable todo rendering in Sphinx

- docs/source/install.rst
> Install docs page: add link to repo

- mumot/__init__.py
I made changes in the  `_roundNumLogsOut()` which solve issue #202.
> Solve issue #202

- mumot/__init__.py
@tbose1 please take a look at this, here are the new methods:
I think `getMasterEquation()` particularly needs your scrutiny, but also check if the way substitutions are handled is consistent and as you feel would be most helpful to the user:
> Add getters for mathematical expressions

- TestNotebooks/MiscTests/MuMoTtest_MultiController.ipynb
- TestNotebooks/MuMoTtest.ipynb
- docs/MuMoTuserManual.ipynb
- mumot/__init__.py
Closes #140 and closes #148 
After quite a lot of work multicontroller functionality now seems quite a lot more robust and flexible, supporting a number of new sophisticated edge cases (see new notebook `MiscTests/MuMoT_MultiController.ipynb`)
All bookmark tests in `MuMoTtest.ipynb` now uncommented.
> Multicontroller fixes

- mumot/__init__.py
> Fix param subscript bug

- README.md
> Fix Travis badge on README (.com -> .org)

- README.md
- TestNotebooks/MiscTests/MuMoTuserManual_for_LabPresentation.ipynb
- docs/MuMoTuserManual.ipynb
- docs/source/development.rst
- mumot/__init__.py
Agreed-on workaround for issue #179
> Switch refs to ReadTheDocs docs site to GH Pages docs site

- mumot/__init__.py
> parseModel warning

- README.md
- docs/source/getting_started.rst
- docs/source/index.rst
> Add overview documentation

- mumot/__init__.py
Fixed points the eigenvalues of which are purely imaginary are not plotted in vector/stream plots.
> Solve issue #257

- TestNotebooks/MiscTests/MuMoTtest_MultiController.ipynb
- TestNotebooks/MiscTests/MuMoTtest_NoiseFixedPoints.ipynb
- TestNotebooks/MuMoTtest.ipynb
- mumot/__init__.py
Made small changes to the MuMoT code to automatically choose suitable matplotlib backend for mac users. Revised test-notebooks by commenting out a few cells - this will decrease code coverage a bit.
> Solve matplotlib-backend related issues

- docs/source/api.rst
- mumot/__init__.py
Moved bifurcation status message to logs and renamed `round_to_1()` to `_round_to_1()`
> Solve issues #250 and #253

- mumot/__init__.py
In field plots: try to calculate noise numerically if analytical calculation fails. But if system has no stable attracting states then numerical calculation of noise is disabled too. Warning messages will be printed above the figure in both cases (if `showNoise=True` was chosen) but the figure will be produced nevertheless (without showing noise). This prevents error messages and maintains continuous workflow.
> Solve issue #254

- docs/source/install.rst
> Docs: correct conda env creation instructions

- README.md
…not the most recent build on any branch!
> Fix Travis badge in README so always shows status of master branch

- mumot/__init__.py
This closes #9 #288
@jarmarshall , please check if ok
> Implemented the download button

- DemoNotebooks/EpidemicsDemo_SIRI.ipynb
- README.md
- docs/MuMoTuserManual.ipynb
- docs/source/about.rst
- docs/source/api.rst
- docs/source/development.rst
- docs/source/getting_started.rst
- mumot/__init__.py
- mumot/_version.py
Closes #309, close #307, closes #306, closes #304, closes #280, closes #252, closes #139, closes #112
> Finalise first release

- mumot/views.py
- setup.py
Closes #231.  Interactivity needs testing.
> Remove matplotlib.pyplot.hold(True) calls and unpin matplotlib version (WIP)

- docs/source/install.rst
> Docs: guard against accidentally installing from PyPI instead of Git clone

- mumot/views.py
> Patched SSA bug

- .travis.yml
- mumot/models.py
- mumot/views.py
- setup.py
Attempts to address #170.  Replaces an abandoned PR (#343).
> Unpin sympy version (WIP)

- mumot/models.py
- mumot/views.py
> Missing rate

- tox.ini
To 120s (see [tox.ini](tox.ini))
Closes #262
> Increase nbval cell exec timeout

- mumot/__init__.py
- mumot/views_oo.py
> Guard against iopub rate limiting warnings

- mumot/views.py
- setup.py
Can revisit the associated Issue (#349) once v1.1.0 is released.
> Partially revert PR 350 as breaks View<->Figure linkages

- README.md
- docs/source/about.rst
- docs/source/getting_started.rst
- mumot/_version.py
To include updates relating to Issue #327
> Prepare release 1.1.2
