DiODeProject/MuMoT

README.md, apt.txt, environment.yml, postBuild
* Fix `environment.yml` so works on Linux
* Ensure LaTeX and graphviz installed using apt when mybinder.org builds Docker container
* Ensure TOC2 (table of contents) Jupyter extension installed by default
* Add button to README for launching User Manual in mybinder.org
See Issue #163
=> mybinder.org compatability

README.md, setup.py, tox.ini
And add a test (in `tox.ini`) that will fail if the user manual Notebook contains output cells.
Addresses Issue #164
=> Remove output cells from user manual Notebook

.travis.yml, tox.ini
Explanation: The tox config in this repo can be used to automatically run tests in an isolated local environment.  For some reason (I forget the specifics) I originally set up Travis CI so it ran a separately defined set of tests and did not just run tox.  
This PR removes the Travis-specific tests from the Travis job config and tells Travis to just run tox, thus unifiying the local and CI service testing mechanisms.
=> Try running just tox within Travis job to unify local and CI testing

.coveragerc, .travis.yml
- Try using Python codecov uploader
- Add check in `.travis.yml` for existence of `.coverage` file 
- Add fairly generic `.coveragerc` config file
Goal is to get the codecov uploader to find and upload the data in .coverage; to date it reports not being able to find any coverage data to upload (https://github.com/DiODeProject/MuMoT/issues/157#issuecomment-425023339)
=> Tweaks to codecov setup

docs/MuMoTuserManual.ipynb, tox.ini
- Corrects an explicit cell ref used to instantiate the variable `model7` (should reference a MuMoT model but previously was just assigned `None`.
- Enables more verbose (per-cell) pytest output
- Disables the display of nbval fails in the browser (problematic on remote machines as there's no display/browser!)
- CI logs should be much more informative now if nbval encounters cells that raise unhandled Exceptions/Errors.
=> Fix user manual cell reference and enable better test output

mumot/__init__.py
Removes a spurious `False` argument in call to `_print_standalone_view_cmd()`
=> Closes #255 (bookmark error)

TestNotebooks/MuMoTtest.ipynb, mumot/__init__.py
The user can now specify through keywords (or via advanced widgets) the simulation details of numerically estimated noise.
To do so, the field controllers and views have been refactored.
Two cells from `TestNotebooks/MuMoTtest.ipynb` have been updated to comply with the structural changes.
=> Fixed issues #223 #277 #256

README.md, tox.ini
Trivial PR created to see if new PRs result in code coverage no longer being quantified for 3rd party code (blacklisted in `tox.ini`; see Issue #249 and PR #298 for details).
=> README: use semantic line endings

mumot/__init__.py
Demonstrates what could be done to address Issue #328
=> Add a small number of type hints

setup.py
Allows use of scipy >= 1.0.0.  
scipy.integrate functionality may have changed so this definitely needs reviewing.
Closes #63
=> Set minimum version of PyDSTool, allowing scipy version to be unpinned

.travis.yml, docs/source/install.rst, tox.ini
Possible now that we're no longer tied to using an old scipy (#338).
=> Enable testing with Python 3.7 with tox and travis-ci.org

mumot/__init__.py, mumot/views.py, setup.py
Since some progress has been made with updating packages I decided to see what happened when all pinnings were removed. The results were encouraging in that issue #210 did not manifest again on Mac in Safari. I played a little and saw only one problem... interacting repeatedly with controller `vector1` in the user manual resulted in the following warning recurring after a while:
```
IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.
Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)
```
@willfurnass could you review, play with these settings, and consider if this is …
=> Unpin package dependencies

mumot/controllers.py, mumot/exceptions.py, mumot/models.py, mumot/utils.py, mumot/views.py
=> Fix sum to1 state

tox.ini
=> tox.ini: ensure pytest does not bail due to spaces in path to mumot pkg dir not being escaped

mumot/views.py
=> Suppress matplotlib deprecation warning in nested multicontrollers

.travis.yml, README.md, docs/source/about.rst, docs/source/getting_started.rst, mumot/_version.py, setup.py
To address #358
Bumped version to 1.1.1 in docs and code.
=> Prepare for v1.1.1 release (re-add ipywidgets to setup.py as removed by mistake)

.travis.yml, docs/source/development.rst
- Travis _shoud_ build and push MuMoT source and binary (wheel) packages to PyPI if the job is triggered by the tagging of a commit rather than a PR (needs testing).
- Sphinx docs updated to reflect how we've been creating releases to date (by just tagging commit, not by creating dedicated release branches).
=> Revise release process inc. docs

setup.py, tox.ini
Temporary workarounds for #377, #378 and #386
=> Pin 'sympy', 'coverage' and 'antlr4-python3-runtime' dependencies

mumot/views.py
XDATA, YDATA and EIGENVALUES have been made lowercase as that's the convention for non-constants.
=> views module: make variables lowercase (convention)

mumot/__init__.py, mumot/views.py
TkAgg no longer seems to be needed on Darwin (OS X); at least issue #158 does not seem to manifest again on OS X without use of TkAgg, so will see if removing it allows issue #391 to be closed
=> Attempt to close #391

docs/source/faq.rst, docs/source/index.rst, setup.cfg
Need to do so without resurrecting #158 (duplicate Figures created upon ipywidget state changes).  
The trick here is to set a minimum version of `ipython` (7.10.0).
Also added a FAQ that recommends users update their dependencies if they
encounter the duplicate Figure issue.
=> Unpin versions of ipykernel, notebook, pyzmq and tornado dependencies; add FAQ

CHANGELOG.md, README.md, docs/source/about.rst, docs/source/getting_started.rst
- Add new version and reserved DOI to citation info in Sphinx docs
- Update mybinder links README.md and Sphinx docs so they reference the `v1.2.0` git ref instead of `master`
AFAICT the only outstanding thing is now creating a `CHANGELOG.md` as per the developer docs.  @jarmarshall Are you happy to do that?
=> Prepare for v1.2.0 release

CHANGELOG.md, README.md, docs/source/about.rst, docs/source/development.rst, docs/source/getting_started.rst
Encountered a problem when releasing v1.2.0 and [PyPI annoyingly does not allow re-using a filename](https://github.com/pypa/packaging-problems/issues/74) so creating v1.2.1.
=> Prepare release v1.2.1
